# Generated by Django 2.0.6 on 2019-08-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_img', models.CharField(max_length=1024)),
                ('u_wallet', models.FloatField(max_length=6)),
            ],
            options={
                'db_table': 'user_detail',
            },
        ),
        migrations.CreateModel(
            name='XMLYUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telenumber', models.CharField(max_length=11, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='userdetail',
            name='u_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.XMLYUser'),
        ),
    ]
