# Generated by Django 2.0.6 on 2019-08-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=100)),
                ('g_img', models.CharField(max_length=200)),
                ('g_price', models.FloatField()),
            ],
            options={
                'db_table': 'goods',
            },
        ),
    ]
