# Generated by Django 2.0.6 on 2019-08-19 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_name', models.CharField(max_length=50)),
                ('de_img', models.CharField(max_length=200)),
                ('mp4', models.CharField(max_length=200)),
                ('de_info', models.CharField(max_length=256)),
                ('de_hits', models.IntegerField()),
                ('de_sub_num', models.IntegerField()),
                ('de_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50)),
                ('d_img', models.CharField(max_length=50)),
                ('d_time', models.DateTimeField(auto_now=True)),
                ('d_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Details')),
            ],
            options={
                'db_table': 'download',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=100)),
                ('g_price', models.FloatField()),
                ('g_img', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Listen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=50)),
                ('l_img', models.CharField(max_length=50)),
                ('l_time', models.DateTimeField(auto_now=True)),
                ('l_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Details')),
            ],
            options={
                'db_table': 'lister',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'navs',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_img', models.CharField(max_length=200)),
                ('pro_intro', models.CharField(max_length=256)),
                ('is_boy', models.BooleanField(default=False)),
                ('is_good', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
                ('pro_type_id', models.IntegerField()),
                ('nav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Nav')),
            ],
            options={
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_img', models.CharField(max_length=200)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Program')),
            ],
            options={
                'db_table': 'wheels',
            },
        ),
        migrations.AddField(
            model_name='listen',
            name='l_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='download',
            name='d_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
        migrations.AddField(
            model_name='details',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Program'),
        ),
        migrations.AddField(
            model_name='car',
            name='c_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Goods'),
        ),
        migrations.AddField(
            model_name='car',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
