# Generated by Django 2.0.6 on 2019-08-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_page', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_time', models.DateTimeField(auto_now=True)),
                ('d_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.Details')),
                ('d_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.XMLYUser')),
            ],
            options={
                'db_table': 'downloads',
            },
        ),
        migrations.CreateModel(
            name='ListenSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.Details')),
                ('l_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.XMLYUser')),
            ],
            options={
                'db_table': 'listensingles',
            },
        ),
    ]
