# Generated by Django 2.0.6 on 2019-08-20 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firstpage', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpage.Mainshow')),
                ('mb_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.QTFMUser')),
            ],
            options={
                'db_table': 'qtfm_mybuy',
            },
        ),
        migrations.CreateModel(
            name='MyCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpage.Mainshow')),
                ('mc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.QTFMUser')),
            ],
            options={
                'db_table': 'qtfm_mycollextion',
            },
        ),
        migrations.CreateModel(
            name='MyDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpage.Mainshow')),
                ('md_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.QTFMUser')),
            ],
            options={
                'db_table': 'qtfm_mydownload',
            },
        ),
        migrations.CreateModel(
            name='MyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mh_radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstpage.Mainshow')),
                ('mh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.QTFMUser')),
            ],
            options={
                'db_table': 'qtfm_myhistory',
            },
        ),
    ]
