# Generated by Django 2.0.6 on 2019-08-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=250)),
                ('type_name', models.CharField(max_length=50)),
                ('type_child', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=256)),
                ('title_id', models.IntegerField()),
                ('text', models.CharField(max_length=100)),
                ('text_detail', models.CharField(max_length=500)),
                ('lector', models.CharField(max_length=20)),
                ('lector_pic', models.CharField(max_length=256)),
                ('loopnumber', models.CharField(max_length=20)),
                ('setnumber', models.CharField(max_length=20)),
                ('xiaoshuo_sex', models.CharField(max_length=5)),
                ('typename_new', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'qtfm_mainshow',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'qtfm_nav',
            },
        ),
        migrations.CreateModel(
            name='Programlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('title_id', models.IntegerField()),
                ('program_name', models.CharField(max_length=50)),
                ('audio_id', models.IntegerField()),
                ('audio_href', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=50)),
                ('loopnumber', models.CharField(max_length=50)),
                ('upload_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'qtfm_programlist',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=256)),
                ('title_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'qtfm_wheel',
            },
        ),
    ]
