# Generated by Django 2.0.6 on 2019-08-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='o_order_num',
            field=models.CharField(max_length=50),
        ),
    ]
