# Generated by Django 2.0.6 on 2019-08-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_name', models.CharField(max_length=50)),
                ('de_img', models.CharField(max_length=200)),
                ('mp4', models.CharField(max_length=200)),
                ('de_info', models.CharField(max_length=256)),
                ('de_hits', models.IntegerField()),
                ('de_sub_num', models.IntegerField()),
                ('de_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'details',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'navs',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_img', models.CharField(max_length=200)),
                ('pro_intro', models.CharField(max_length=256)),
                ('is_boy', models.BooleanField()),
                ('is_good', models.BooleanField()),
                ('is_vip', models.BooleanField()),
                ('pro_type_id', models.IntegerField()),
                ('nav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.Nav')),
            ],
            options={
                'db_table': 'programs',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_img', models.CharField(max_length=200)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home_page.Program')),
            ],
            options={
                'db_table': 'wheels',
            },
        ),
        migrations.AddField(
            model_name='details',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.Program'),
        ),
    ]
